### ISSUE TITLE
Intercept and AutoHotkey don't  work on certain Programs

### ISSUE THREAD

**Issue by maherdsh** [TaranVH/2nd-keyboard#103]
I design 3D using various programs and having shortcuts for tools is awesome but I had an issue,
ZBrush overwrites the Intercept and stops it from working but while the program is opened and you go to the desktop Intercept and AutoHotkey will work again. 
Matrix 3D will stop both Intercept and AutoHotkey and everything works again fine once it's close.
Any Advice/Solution,
Thanks 
![b vncvnvbn](https://user-images.githubusercontent.com/6746952/71708199-679bf680-2e2a-11ea-9536-dc57ffaa86ea.JPG)

**Comment by TaranVH** [comment]
The only other program I know of that messes with autohotkey is Xsplit. Because it's lsitening to GLOBAL shortcuts... no matter what program you're in, if you hit ALT F1 or something, then it'll start recording your screen. And it does this before AutoHotKey has a chance to notice the keystroke and block it or whatever.
I suspect your issue is something like that.

Did you use the lines
#InstallKeybdHook
#UseHook On
at the top of your script?

If the hook doesn't work, I don't know what will.
Your only options are gonna be built into the keyboard you use. So razer, corsair, QMK, etc.

**Comment by maherdsh** [comment]
Hi TaranVH,
Yeah I'm using the AutoHotKey that's provided in gethub (Full_extra_keyboard).
The commands #InstallKeybdHook #UseHook On and at the top lines.
Like you said some programs are overwriting the AutoHotKey.
Thanks for the reply.

**Comment by PotatoJet** [comment]
Use QMK!
