### ISSUE TITLE
Issue when opening ''ALL_MULTIPLE_KEYBOARD_ASSIGNMENTS.ahk''

### ISSUE THREAD

**Issue by Edvards55** [TaranVH/2nd-keyboard#106]
![TARAN FIX IT!](https://user-images.githubusercontent.com/26838498/73615172-52271180-460e-11ea-9adf-61791800a0e7.PNG)

**Comment by TaranVH** [comment]
search that .ahk script for "ACC." there are instructions. you have to install it, or remove the code that uses it.

**Comment by Edvards55** [comment]
The only thing in the code that contains ''Acc'' is the word ''Acceleration'' 5 times

**Comment by Edvards55** [comment]
Also Line 1634 in the code is blank

**Comment by TaranVH** [comment]
That's because you're looking in the wrong script. don't forget that it
#include s a few others.
Almost_All_Windows_Functions.ahk
is where you want to look.

; Script to activate any given firefox tab...
;This requires the ACC library, which you have to install into AutoHotKey
(it's pretty easy, just scroll to the top of this page and follow the
instructions.)
;https://autohotkey.com/boards/viewtopic.php?f=6&t=26947&p=139114#p139114
; calling the function looks like this:

I've already made a note in
ALL_MULTIPLE_KEYBOARD_ASSIGNMENTS.ahk
but it hasn't been pushed to github yet.
happy scripting!
