### ISSUE TITLE
QWEADZXC Keys take me to desktop! (Win10)

### ISSUE THREAD

**Issue by Swagbot79** [TaranVH/2nd-keyboard#17]
The Q, W, E, A, D, Z, X,C Keys take me to the desktop when I press them instead of doing the wipe effects!

**Comment by TaranVH** [comment]
Watch this video. It requires a second timeline. It's a real pain in the ass to set up.
It doesn't even work very well on my computer.
https://www.youtube.com/watch?v=L05KRribWt0

I will implement a much BETTER system that uses multiple saved clipboards, instead of having to freshly COPY the transitions every single time.
