### ISSUE TITLE
How can i launch Interception during startup and make it run in the background?

### ISSUE THREAD

**Issue by weizenyang** [TaranVH/2nd-keyboard#66]

**Comment by TaranVH** [comment]
check the pull requests and solved issues I believe someone made something that does that.
[actually, I just checked, and saw no such thing. I remember SOMETHING about it, though...]
I have not yet implemented it myself - because i have to wait for lots of stuff to load during startup anyway.
all i have now is a shortcut to it in my startup folder - but this does not hit "y" for me.
Let me know if you figure it out!

**Comment by XLENet** [comment]
Shouldn't this be as easy as configuring a Windows startup task?

**Comment by TaranVH** [comment]
lol maybe! Feel free to share with the class!
I've never bothered to figure it out, because the PC is always loading a bunch of other stuff at that time anyway, so it does not slow me down to have to do it manually.

**Comment by Jerreu** [comment]
I suppose you mean launching the Lua Macros script, in which case, you could, as I did, put your AHK script into Autostart and then do something like this: `
Run --File Path of your Lua Script--, , , Lua
CoordMode, Mouse, Screen
MouseGetPos, txpos, typos
Sleep, 500
Click, --coordinates of the "Play" Button; You can get them using Window Spy, which comes with Ahk--
Click, --coordinates of the Minimize Button; this will hide it and put it into the tray, because lmc.minimizeToTray is set to true in the Lua File--
MouseMove, %txpos%, %typos%`

**Comment by bardsnight** [comment]
About the "hit on Y", you can just create a batch with 

```
start /min intercept.exe /apply
minimize
```

The /apply does the thing about the need to hit y.
I still haven't figured out how to make it run on tray, or anything like that, but as it starts and stays minimized I just fixed it at the toolbar al it always start and I forget it.
![image](https://user-images.githubusercontent.com/51341598/58918367-62de5b00-8700-11e9-8200-8d378a9722af.png)

**Comment by bardsnight** [comment]
Then just paste their shortcuts at the startup folder
![image](https://user-images.githubusercontent.com/51341598/58918405-85707400-8700-11e9-8feb-80458afc816f.png)

**Comment by oliver-ni** [comment]
To solve the problem of the hanging command line window, try this vbscript:

    Set WshShell = WScript.CreateObject("WScript.Shell")
    WshShell.Run "intercept.exe /apply", 0, true

**Comment by MayhemBill** [comment]
This saved my life. Packing intercept into the vbs and setting it to autorun on startup makes this a whole lot easier.

**Comment by TaranGenius** [comment]
> Then just paste their shortcuts at the startup folder
> ![image](https://user-images.githubusercontent.com/51341598/58918405-85707400-8700-11e9-8feb-80458afc816f.png)
> 
> Edit: Keeep in mind that you should put the original batch launch file at Intercept.exe root folder.

Which you use now?Intercept.exe Or Hasu_USB?

**Comment by TaranGenius** [comment]
> This saved my life. Packing intercept into the vbs and setting it to autorun on startup makes this a whole lot easier.

Which you use now?Intercept.exe Or Hasu_USB?

**Comment by TaranGenius** [comment]
> Shouldn't this be as easy as configuring a Windows startup task?

Which you use now?Intercept.exe Or Hasu_USB?

**Comment by MayhemBill** [comment]
I just got a Streamdeck. Way easier.

**Comment by PotatoJet** [comment]
#96 See it

**Comment by PotatoJet** [comment]
Please close this issue!!!

**Comment by Agasthya7** [comment]
> This saved my life. Packing intercept into the vbs and setting it to autorun on startup makes this a whole lot easier.

Can you elaborate on how I can make the vbs file run on startup. Tried a lot of ways but it just doesn't run

**Comment by daominh89** [comment]
> > This saved my life. Packing intercept into the vbs and setting it to autorun on startup makes this a whole lot easier.
> 
> Can you elaborate on how I can make the vbs file run on startup. Tried a lot of ways but it just doesn't run

So you first create a vbs file in intercept original folder with the following code:
```
Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.Run "intercept.exe /apply", 0, true
```

Then create a shortcut in startup folder that point to this vbs file
