### ISSUE TITLE
Numpad doesn't Work

### ISSUE THREAD

**Issue by Odgy56** [TaranVH/2nd-keyboard#81]
I have every key working except the numpad or keys like scroll lock the only thing that I can think of is that I am using a Uk keyboard so the keys might not line up with the key numbers.

![advent keyboard2](https://user-images.githubusercontent.com/47379670/52326745-9c68b900-29e1-11e9-9e62-99614990ce4d.jpg)

**Comment by TaranVH** [comment]
Lololol.
Which method are you using? Interception?

**Comment by Matesaktesak** [comment]
If you are using intercept, you might need to remap these keys manually - Tarans file doesn't include them in foreign layouts.

**Comment by Odgy56** [comment]
I am using LuaMacros

**Comment by Matesaktesak** [comment]
Oh

**Comment by Matesaktesak** [comment]
Is there any reason why you aren't using intercept?

**Comment by Wegerich** [comment]
When you press these keys, do you see that the Lua console records the
keystrokes? The numpad should work with a UK keyboard because the keycodes
should be the same (at least I didn't really have any problems)

Is it possible that you have your "NumLock" key/mode disabled? Do the keys
work when the 2nd keyboard code is not running?

**Comment by Odgy56** [comment]
I managed to get it to work. I had a conflicting AHK script

**Comment by TaranVH** [comment]
har har
