### ISSUE TITLE
Use 2nd keyboard for Keybinds?

### ISSUE THREAD

**Issue by MayhemBill** [TaranVH/2nd-keyboard#92]
Is it possible to set the second keyboard to be used outside of AHK? I've been tinkering around and it seems like if I remove the key from ahk it just reverts back to a standard keypress.

**Comment by TaranVH** [comment]
Using which system?

Short answer: No.

Long answer: If you, for example, set up your 2nd keyboard such that pressing "G" will send an F21 keystroke instead, then only an application that is capable of having a command assigned to F21, will be triggered by that keystroke. Premiere, for example, is capable of having commands assigned to F13 through F24. So that's twelve commands that you could set up, that do not require AHK to work. However, that is as far as you could go.
Sooooo, just use AHK ;)

**Comment by MayhemBill** [comment]
I'm using Intercept Interception and AHK, I have 2 keyboards setup using this method and have various things bound through the keys but I've run into the issue of certain applications only accept keybinds and nothing else. Such as WeMod, I use it to mess with games and make them downright stupid in terms of gameplay, but I'm getting to the point where all the keybinds and the keys for the game no longer fit nicely on one keyboard.

**Comment by TaranVH** [comment]
I'm not sure what you mean by "keybinds."
Do you mean, key assignments? Like, in Minecraft, SHIFT is used to crouch, but if you wanted to, you could re-assign it (re-BIND it) to "C" or something?

Because, that's how all applications work. They accept keyboard input, and mouse input.
And my AHK scripts work by outputting keyboard and mouse commands.
with AHK you can also send multiple keys at a time, or send one, wait a little while, send another one, wait, send another one, etc. You know, a macro. But each of those is a key that needs to be binded in the application you're trying to control.

So I really don't know what you mean when you say that applications "only" accept keybinds. What have you been doing aside from that? Do you know something that I don't? Is there some super cool way that AHK can directly interface with an application, without the need to send keyboard commands to it?

Or perhaps, are you just saying that some games have AHK cheat detection built-in, which prevents you from using AHK in them?

**Comment by MayhemBill** [comment]
Okay so I'm not 100% sure what I was talking about yesterday, I was tired and was making up things that intercept was doing. I thought that would duplicate the amount of keys I had, magically making my 2x108 keys into 216 different keys. Some applications don't detect multiple key inputs as valid assignments, so I was limited to my standard 108 and the f13+ keys. I was trying to expand that number for ease of use with certain games.

**Comment by TaranVH** [comment]
Correct.
No application that I know of will accept "F13 Q" as a valid input. It will
accept "Q", it will accept "CTRL Q", and it might accept "F13", but only
autohotkey can listen for "F13 Q" and turn that into a useful command.

**Comment by MayhemBill** [comment]
here's another question, using the Intercept method? How Meta can I go? Like Can I press two keys at once to obtain a third key bind?

example: 
A:: Chrome
B:: Firefox
A+B::Opera

**Comment by TaranVH** [comment]
I'm not sure. Try it!
~A & B::msgbox, launch opera
I suspect that it won't work. You'll end up launching chrome and opera, or
firefox and opera.

**Comment by MayhemBill** [comment]
Correct, it runs both A and B, and ignores the AB entirely.
